[package]
name = "rustshot-gtk"
version = "0.7.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
nix = "0.15.0"
gtk = { package = "gtk4", version = "0.10", features = ["v4_20"] }
pangocairo = "0.21"
once_cell = "*"
